version: 2.1
orbs:
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@2.2.5

executors:
  node-with-postgres:
    docker:
      - image: cimg/node:22.14
      - image: cimg/postgres:16.14
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: challenge_cursor_test  

jobs:
  build_and_test:
    executor: node-with-postgres
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: npm run test:coverage
          name: Run tests with coverage
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths: ['.']
      - coveralls/upload:
          parallel: false
          flag_name: Unit Tests
          verbose: true

workflows:
  build_test_deploy:
    jobs:
      - build_and_test